services:
  db:
    image: mariadb:11
    container_name: mariadb_cp
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: codigos_postales
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./Data/CPdescargatxt/CPdescarga.txt:/docker-entrypoint-initdb.d/CPdescarga.txt

  app:
    build: .
    container_name: flask_cp
    restart: always
    environment:
      DB_HOST: db
      DB_USER: flaskuser
      DB_PASS: flaskpass
      DB_NAME: codigos_postales
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:

